import json
import requests
import re
from urllib.parse import urljoin

# গ্লোবাল লিস্ট যেখানে সব চ্যানেল একসাথে জমা হবে (কোনো ফিল্টারিং ছাড়া)
all_m3u_lines = ["#EXTM3U\n# Playlist generated by Automated Termux Multi-Scanner"]

# =====================================================================
# SERVER 1: LIVETV EXTRACTOR (IP: 198.195.239.50)
# =====================================================================
def extract_m3u_from_livetv():
    base_url = "http://198.195.239.50/"
    print("\n" + "="*70)
    print("  📺 [1/3] Scanning LiveTV (198.195.239.50)...")
    print("="*70)
    
    try:
        response = requests.get(base_url, timeout=10)
        response.raise_for_status()
        html_content = response.text
        
        json_urls = []
        json_patterns = [
            r'fetch\s*\(\s*["\']([^"\']+\.json)["\']\s*\)',
            r'src\s*=\s*["\']([^"\']+\.json)["\']',
            r'"([^"]+\.json)"',
        ]
        for pattern in json_patterns:
            matches = re.findall(pattern, html_content)
            for match in matches:
                if match not in json_urls: json_urls.append(match)
        
        tv_json = None
        for j in json_urls:
            if 'channel' in j.lower() or 'tv' in j.lower():
                tv_json = j
                break
        
        if tv_json:
            json_url = urljoin(base_url, tv_json)
            json_response = requests.get(json_url, timeout=10)
            data = json_response.json()
            channels = data.get("channels", [])
            
            count = 0
            # একই নামের চ্যানেলগুলোকে ট্র্যাক করার জন্য কাউন্টার ডিকশনারি
            name_tracker = {}
            
            for ch in channels:
                if ch.get("status") == "hidden": continue
                original_name = ch.get("name", "Unknown").strip()
                url = ch.get("url", "")
                logo = ch.get("logo", "")
                category = ch.get("category", "LiveTV 198")
                
                if not url: continue
                if not url.startswith('http'): url = urljoin(base_url, url)
                
                # যদি নাম আগে এসে থাকে তবে পাশে (1), (2) যোগ করবে
                if original_name in name_tracker:
                    name_tracker[original_name] += 1
                    display_name = f"{original_name} ({name_tracker[original_name]})"
                else:
                    name_tracker[original_name] = 1
                    display_name = original_name
                
                all_m3u_lines.append(f'#EXTINF:-1 group-title="{category}" logo="{logo}",{display_name}\n{url}')
                count += 1
            print(f"  ✅ Added {count} channels from LiveTV 198.")
    except Exception as e:
        print(f"  ❌ LiveTV 198 Error: {e}")

# =====================================================================
# SERVER 2: TEXAS TV EXTRACTOR (IP: 10.99.99.99)
# =====================================================================
def extract_texas_stream_url(player_url):
    try:
        response = requests.get(player_url, timeout=5)
        html = response.text
        patterns = [
            r'file\s*:\s*["\']([^"\']+\.m3u8[^"\']*)["\']',
            r'src\s*=\s*["\']([^"\']+\.m3u8[^"\']*)["\']',
            r'["\']([^"\']+\.m3u8[^"\']*)["\']',
        ]
        for pattern in patterns:
            matches = re.findall(pattern, html)
            if matches:
                url = matches[0]
                if not url.startswith('http'): url = urljoin('http://10.99.99.99/', url)
                return url
        return None
    except:
        return None

def extract_all_texas_channels():
    base_url = "http://10.99.99.99/"
    print("\n" + "="*70)
    print("  📺 [2/3] Scanning TEXAS TV (10.99.99.99)...")
    print("="*70)
    
    try:
        response = requests.get(base_url, timeout=5)
        html = response.text
        
        li_pattern = r'<li class="([^"]+)">\s*<a[^>]*onclick="view\.location\.href=\'([^\']+)\'"[^>]*>\s*<img src="([^"]+)" alt="([^"]+)"'
        matches = re.findall(li_pattern, html)
        
        count = 0
        name_tracker = {}
        
        for match in matches:
            classes, stream_url, img_src, original_name = match[0].split(), match[1], match[2], match[3].strip()
            category = "Texas TV"
            for cls in classes:
                if cls not in ['All', 'channel']:
                    category = f"Texas - {cls.capitalize()}"
                    break
            
            player_full_url = urljoin(base_url, stream_url)
            real_url = extract_texas_stream_url(player_full_url)
            
            if real_url:
                if original_name in name_tracker:
                    name_tracker[original_name] += 1
                    display_name = f"{original_name} ({name_tracker[original_name]})"
                else:
                    name_tracker[original_name] = 1
                    display_name = original_name
                    
                all_m3u_lines.append(f'#EXTINF:-1 group-title="{category}" logo="{urljoin(base_url, img_src)}",{display_name}\n{real_url}')
                print(f"    ✅ Found: {display_name}")
                count += 1
        print(f"  ✅ Added {count} channels from Texas TV.")
    except Exception as e:
        print(f"  ❌ Texas TV Error: {e}")

# =====================================================================
# SERVER 3: NEW LIVETV EXTRACTOR (IP: 172.17.50.112)
# =====================================================================
def extract_from_new_livetv():
    base_url = "http://172.17.50.112/"
    print("\n" + "="*70)
    print("  📺 [3/3] Scanning NEW LiveTV (172.17.50.112)...")
    print("="*70)
    
    count = 0
    name_tracker = {}
    target_files = ["js/main.js", "js/app.js"]
    
    for file_path in target_files:
        full_url = urljoin(base_url, file_path)
        try:
            res = requests.get(full_url, timeout=5)
            if res.status_code != 200: continue
            js_content = res.text
            
            item_pattern = r'\{[^{}]*(?:name|title|label)\s*:\s*["\']([^"\']+)["\'][^{}]*(?:file|src|url)\s*:\s*["\']([^"\']+)["\'][^{}]*\}'
            matches = re.findall(item_pattern, js_content)
            
            if not matches:
                item_pattern_reverse = r'\{[^{}]*(?:file|src|url)\s*:\s*["\']([^"\']+)["\'][^{}]*(?:name|title|label)\s*:\s*["\']([^"\']+)["\'][^{}]*\}'
                reverse_matches = re.findall(item_pattern_reverse, js_content)
                matches = [(m[1], m[0]) for m in reverse_matches]
                
            if not matches:
                general_matches = re.findall(r'(?:name|title)["\']?\s*:\s*["\']([^"\']+)["\'].*?["\']?(?:file|src|url)["\']?\s*:\s*["\']([^"\']+\.m3u8[^"\']*)["\']', js_content, re.DOTALL)
                if general_matches: matches = general_matches
            
            # সেট (Set) এর ঝামেলা বাদ দিয়ে সরাসরি লুপে সব ম্যাচ নেওয়া হচ্ছে
            for original_name, url in matches:
                original_name = original_name.strip()
                if ".m3u8" in url or "stream" in url or "http" in url:
                    if not url.startswith('http'): url = urljoin(base_url, url)
                    
                    if original_name in name_tracker:
                        name_tracker[original_name] += 1
                        display_name = f"{original_name} ({name_tracker[original_name]})"
                    else:
                        name_tracker[original_name] = 1
                        display_name = original_name
                        
                    all_m3u_lines.append(f'#EXTINF:-1 group-title="LiveTV 172",{display_name}\n{url}')
                    print(f"    ✅ Found: {display_name}")
                    count += 1
        except:
            pass
    print(f"  ✅ Added {count} channels from LiveTV 172.")

# =====================================================================
# MAIN RUNNER
# =====================================================================
if __name__ == "__main__":
    extract_m3u_from_livetv()
    extract_all_texas_channels()
    extract_from_new_livetv()
    
    final_filename = "all_channels.m3u"
    with open(final_filename, 'w', encoding='utf-8') as f:
        f.write("\n".join(all_m3u_lines))
        
    print("\n" + "="*70)
    print(f"  🎉 SUCCESS! Consolidated M3U Playlist Saved To: {final_filename}")
    print("="*70)
